In [1]:
##Here is an exercise for me to fit curves on images
## Trying too hard. Start with an easier example. This imports the noisey asf data from an IMAGE
## Start with a .csv and move up. We'll be back for this

In [19]:
import scipy
from numpy import asarray
from PIL import Image
import os
import matplotlib
import pandas

In [5]:
cwd = os.getcwd()

print(cwd)

/home/mauasus/ml_projects


In [12]:
image = Image.open(cwd+'/SeismicImage.jpg')
print(image.format)
print(image.size)
print(image.mode)

JPEG
(373, 359)
RGB


In [13]:
bw_image = Image.open(cwd+'/SeismicImage.jpg').convert('L')

bw_image.show()

display-im6.q16: unable to open X server `:0' @ error/display.c/DisplayImageCommand/412.


In [16]:
numpydata = asarray(bw_image)
print(type(numpydata))
print(numpydata.shape)

<class 'numpy.ndarray'>
(359, 373)


In [17]:
diffdata = asarray(image)
print(type(diffdata))
print(diffdata.shape)
#So these are actually different datasets

<class 'numpy.ndarray'>
(359, 373, 3)


In [18]:
print(numpydata)

[[208 255 255 ... 237 255 255]
 [255 242 228 ... 255 255 249]
 [214  19   0 ... 205 250 253]
 ...
 [249 255 255 ... 243 238 255]
 [246 254 255 ... 255 252 255]
 [255 249 220 ...   1   7 235]]
